-- request_logs: middleware traffic log (middleware.ts writes via PostgREST).
-- The table was created ad hoc in the Supabase dashboard on 2026-07-25; this
-- file captures the DDL for the record. Blocked rows are SAMPLED at 1 in 20
-- by the middleware since 2026-08-01 (multiply blocked counts by 20).

-- 1) Original table (already exists in prod; kept here for reference/rebuild).
create table if not exists request_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  path text not null,
  referer text,
  referer_host text,
  ua text,
  is_bot boolean not null default false,
  bot_name text,
  blocked boolean not null default false,
  country text
);

alter table request_logs enable row level security;

-- 2) Hashed client IP (first 8 bytes of sha256(IP_HASH_SALT + ip), hex).
--    Lets us count unique clients per cohort without storing raw IPs.
alter table request_logs add column if not exists ip_hash text;

create index if not exists idx_request_logs_created_at
  on request_logs (created_at);

-- 3) Retention: the table grew ~197k rows in its first 7 days. Keep 30 days.
select cron.schedule(
  'purge-request-logs',
  '15 9 * * *',
  $$delete from request_logs where created_at < now() - interval '30 days'$$
);

-- To inspect or undo the job:
--   select * from cron.job where jobname = 'purge-request-logs';
--   select cron.unschedule('purge-request-logs');
