// GENERATED by scripts/generate-chris-paul-data.ts. Do not hand-edit.
//
// Chris Paul's season-by-season regular season arc (per-game and per-36 rates, both
// computed from summed season totals so a midseason trade is one season), plus the
// all-time career assist leaderboard computed from a full scan of regularseasonstats.
// Ranks are positions in that full scan, not within a curated peer list.
//
// Paul debuted in 2006, so all of his figures clear the era-coverage gates in
// lib/percentiles.ts. Steals exist as an official stat only from 1973-74, so the
// all-time steals rank covers the steal era. Playoff figures cover 149 games.
//
// Box scores: Eoin A Moore's Kaggle dataset (CC0 1.0), spot-checked by hand against
// Basketball Reference. Data current through the 2026 season.

export interface CareerSeason {
  season: number;
  label: string;
  team: string;
  games: number;
  minutesPerGame: number;
  pointsPerGame: number;
  assistsPerGame: number;
  stealsPerGame: number;
  pointsPer36: number;
  assistsPer36: number;
}

export interface LeaderCareer {
  personId: number;
  name: string;
  seasons: number;
  games: number;
  points: number;
  assists: number;
  steals: number;
  assistsPerGame: number;
}

export const seasons: CareerSeason[] = [
  {
    "season": 2006,
    "label": "2005-06",
    "team": "Hornets",
    "games": 78,
    "minutesPerGame": 35.5,
    "pointsPerGame": 16.1,
    "assistsPerGame": 7.8,
    "stealsPerGame": 2.24,
    "pointsPer36": 16.3,
    "assistsPer36": 7.9
  },
  {
    "season": 2007,
    "label": "2006-07",
    "team": "Hornets",
    "games": 64,
    "minutesPerGame": 36.3,
    "pointsPerGame": 17.3,
    "assistsPerGame": 8.9,
    "stealsPerGame": 1.84,
    "pointsPer36": 17.1,
    "assistsPer36": 8.8
  },
  {
    "season": 2008,
    "label": "2007-08",
    "team": "Hornets",
    "games": 80,
    "minutesPerGame": 37.1,
    "pointsPerGame": 21.1,
    "assistsPerGame": 11.6,
    "stealsPerGame": 2.71,
    "pointsPer36": 20.4,
    "assistsPer36": 11.2
  },
  {
    "season": 2009,
    "label": "2008-09",
    "team": "Hornets",
    "games": 78,
    "minutesPerGame": 38,
    "pointsPerGame": 22.8,
    "assistsPerGame": 11,
    "stealsPerGame": 2.77,
    "pointsPer36": 21.6,
    "assistsPer36": 10.5
  },
  {
    "season": 2010,
    "label": "2009-10",
    "team": "Hornets",
    "games": 45,
    "minutesPerGame": 37.5,
    "pointsPerGame": 18.7,
    "assistsPerGame": 10.7,
    "stealsPerGame": 2.13,
    "pointsPer36": 17.9,
    "assistsPer36": 10.2
  },
  {
    "season": 2011,
    "label": "2010-11",
    "team": "Hornets",
    "games": 80,
    "minutesPerGame": 35.5,
    "pointsPerGame": 15.9,
    "assistsPerGame": 9.8,
    "stealsPerGame": 2.35,
    "pointsPer36": 16.1,
    "assistsPer36": 9.9
  },
  {
    "season": 2012,
    "label": "2011-12",
    "team": "Clippers",
    "games": 60,
    "minutesPerGame": 35.9,
    "pointsPerGame": 19.8,
    "assistsPerGame": 9.1,
    "stealsPerGame": 2.53,
    "pointsPer36": 19.9,
    "assistsPer36": 9.1
  },
  {
    "season": 2013,
    "label": "2012-13",
    "team": "Clippers",
    "games": 70,
    "minutesPerGame": 32.9,
    "pointsPerGame": 16.9,
    "assistsPerGame": 9.7,
    "stealsPerGame": 2.41,
    "pointsPer36": 18.6,
    "assistsPer36": 10.6
  },
  {
    "season": 2014,
    "label": "2013-14",
    "team": "Clippers",
    "games": 62,
    "minutesPerGame": 34.5,
    "pointsPerGame": 19.1,
    "assistsPerGame": 10.7,
    "stealsPerGame": 2.48,
    "pointsPer36": 19.9,
    "assistsPer36": 11.2
  },
  {
    "season": 2015,
    "label": "2014-15",
    "team": "Clippers",
    "games": 82,
    "minutesPerGame": 34.3,
    "pointsPerGame": 19.1,
    "assistsPerGame": 10.2,
    "stealsPerGame": 1.9,
    "pointsPer36": 20,
    "assistsPer36": 10.7
  },
  {
    "season": 2016,
    "label": "2015-16",
    "team": "Clippers",
    "games": 74,
    "minutesPerGame": 32.2,
    "pointsPerGame": 19.5,
    "assistsPerGame": 10,
    "stealsPerGame": 2.05,
    "pointsPer36": 21.9,
    "assistsPer36": 11.2
  },
  {
    "season": 2017,
    "label": "2016-17",
    "team": "Clippers",
    "games": 61,
    "minutesPerGame": 31,
    "pointsPerGame": 18.1,
    "assistsPerGame": 9.2,
    "stealsPerGame": 1.95,
    "pointsPer36": 21,
    "assistsPer36": 10.7
  },
  {
    "season": 2018,
    "label": "2017-18",
    "team": "Rockets",
    "games": 58,
    "minutesPerGame": 31.3,
    "pointsPerGame": 18.6,
    "assistsPerGame": 7.9,
    "stealsPerGame": 1.66,
    "pointsPer36": 21.4,
    "assistsPer36": 9
  },
  {
    "season": 2019,
    "label": "2018-19",
    "team": "Rockets",
    "games": 58,
    "minutesPerGame": 31.6,
    "pointsPerGame": 15.6,
    "assistsPerGame": 8.2,
    "stealsPerGame": 1.97,
    "pointsPer36": 17.8,
    "assistsPer36": 9.3
  },
  {
    "season": 2020,
    "label": "2019-20",
    "team": "Thunder",
    "games": 70,
    "minutesPerGame": 31,
    "pointsPerGame": 17.6,
    "assistsPerGame": 6.7,
    "stealsPerGame": 1.59,
    "pointsPer36": 20.4,
    "assistsPer36": 7.8
  },
  {
    "season": 2021,
    "label": "2020-21",
    "team": "Suns",
    "games": 70,
    "minutesPerGame": 31,
    "pointsPerGame": 16.4,
    "assistsPerGame": 8.9,
    "stealsPerGame": 1.41,
    "pointsPer36": 19.1,
    "assistsPer36": 10.3
  },
  {
    "season": 2022,
    "label": "2021-22",
    "team": "Suns",
    "games": 65,
    "minutesPerGame": 32.4,
    "pointsPerGame": 14.7,
    "assistsPerGame": 10.8,
    "stealsPerGame": 1.86,
    "pointsPer36": 16.4,
    "assistsPer36": 12
  },
  {
    "season": 2023,
    "label": "2022-23",
    "team": "Suns",
    "games": 59,
    "minutesPerGame": 31.5,
    "pointsPerGame": 13.9,
    "assistsPerGame": 8.9,
    "stealsPerGame": 1.54,
    "pointsPer36": 15.8,
    "assistsPer36": 10.1
  },
  {
    "season": 2024,
    "label": "2023-24",
    "team": "Warriors",
    "games": 58,
    "minutesPerGame": 25.9,
    "pointsPerGame": 9.2,
    "assistsPerGame": 6.8,
    "stealsPerGame": 1.21,
    "pointsPer36": 12.8,
    "assistsPer36": 9.4
  },
  {
    "season": 2025,
    "label": "2024-25",
    "team": "Spurs",
    "games": 82,
    "minutesPerGame": 27.8,
    "pointsPerGame": 8.8,
    "assistsPerGame": 7.4,
    "stealsPerGame": 1.26,
    "pointsPer36": 11.4,
    "assistsPer36": 9.6
  },
  {
    "season": 2026,
    "label": "2025-26",
    "team": "Clippers",
    "games": 16,
    "minutesPerGame": 14,
    "pointsPerGame": 2.9,
    "assistsPerGame": 3.3,
    "stealsPerGame": 0.69,
    "pointsPer36": 7.6,
    "assistsPer36": 8.5
  }
];

// Top 8 all-time in career assists, in order.
export const leaders: LeaderCareer[] = [
  {
    "personId": 304,
    "name": "John Stockton",
    "seasons": 19,
    "games": 1504,
    "points": 19711,
    "assists": 15806,
    "steals": 3265,
    "assistsPerGame": 10.5
  },
  {
    "personId": 101108,
    "name": "Chris Paul",
    "seasons": 21,
    "games": 1370,
    "points": 23058,
    "assists": 12552,
    "steals": 2728,
    "assistsPerGame": 9.2
  },
  {
    "personId": 467,
    "name": "Jason Kidd",
    "seasons": 19,
    "games": 1391,
    "points": 17529,
    "assists": 12091,
    "steals": 2684,
    "assistsPerGame": 8.7
  },
  {
    "personId": 2544,
    "name": "LeBron James",
    "seasons": 23,
    "games": 1622,
    "points": 43440,
    "assists": 12016,
    "steals": 2417,
    "assistsPerGame": 7.4
  },
  {
    "personId": 201566,
    "name": "Russell Westbrook",
    "seasons": 18,
    "games": 1301,
    "points": 27176,
    "assists": 10351,
    "steals": 2038,
    "assistsPerGame": 8
  },
  {
    "personId": 959,
    "name": "Steve Nash",
    "seasons": 18,
    "games": 1213,
    "points": 17389,
    "assists": 10335,
    "steals": 899,
    "assistsPerGame": 8.5
  },
  {
    "personId": 349,
    "name": "Mark Jackson",
    "seasons": 17,
    "games": 1296,
    "points": 12489,
    "assists": 10334,
    "steals": 1608,
    "assistsPerGame": 8
  },
  {
    "personId": 77142,
    "name": "Magic Johnson",
    "seasons": 13,
    "games": 906,
    "points": 17707,
    "assists": 10142,
    "steals": 1597,
    "assistsPerGame": 11.2
  }
];

// Deliberately not `as const`: the article compares ranks and matches season labels at
// runtime, and literal-narrowed values make those checks unreachable to the compiler.
export const context: {
  seasonCount: number;
  firstSeasonLabel: string;
  finalSeasonLabel: string;
  firstTeam: string;
  finalTeam: string;
  games: number;
  points: number;
  assists: number;
  steals: number;
  pointsPerGame: number;
  assistsPerGame: number;
  stealsPerGame: number;
  teamCount: number;
  peakScoringLabel: string;
  peakScoringPoints: number;
  peakScoringAssists: number;
  peakAssistsLabel: string;
  peakAssistsPerGame: number;
  peakScoringRateLabel: string;
  peakPointsPer36: number;
  peakAssistRateLabel: string;
  peakAssistRatePer36: number;
  peakAssistRateSeasonNumber: number;
  peakAssistRateTeam: string;
  rookiePointsPerGame: number;
  rookieStealsPerGame: number;
  rookieAssistsPer36: number;
  finalGames: number;
  finalPointsPerGame: number;
  finalMinutesPerGame: number;
  finalPointsPer36: number;
  finalAssistsPer36: number;
  full82Count: number;
  full82FirstLabel: string;
  full82LastLabel: string;
  full82LastSeasonNumber: number;
  full82LastTeam: string;
  playoffGames: number;
  playoffPoints: number;
  playoffAssists: number;
  playoffPointsPerGame: number;
  playoffAssistsPerGame: number;
  leaderCount: number;
  assistsAllTimeRank: number;
  stealsAllTimeRank: number;
  pointsRankAmongLeaders: number;
  assistLeaderName: string;
  assistsBehindLeader: number;
} = {
  "seasonCount": 21,
  "firstSeasonLabel": "2005-06",
  "finalSeasonLabel": "2025-26",
  "firstTeam": "Hornets",
  "finalTeam": "Clippers",
  "games": 1370,
  "points": 23058,
  "assists": 12552,
  "steals": 2728,
  "pointsPerGame": 16.8,
  "assistsPerGame": 9.2,
  "stealsPerGame": 2,
  "teamCount": 7,
  "peakScoringLabel": "2008-09",
  "peakScoringPoints": 22.8,
  "peakScoringAssists": 11,
  "peakAssistsLabel": "2007-08",
  "peakAssistsPerGame": 11.6,
  "peakScoringRateLabel": "2015-16",
  "peakPointsPer36": 21.9,
  "peakAssistRateLabel": "2021-22",
  "peakAssistRatePer36": 12,
  "peakAssistRateSeasonNumber": 17,
  "peakAssistRateTeam": "Suns",
  "rookiePointsPerGame": 16.1,
  "rookieStealsPerGame": 2.24,
  "rookieAssistsPer36": 7.9,
  "finalGames": 16,
  "finalPointsPerGame": 2.9,
  "finalMinutesPerGame": 14,
  "finalPointsPer36": 7.6,
  "finalAssistsPer36": 8.5,
  "full82Count": 2,
  "full82FirstLabel": "2014-15",
  "full82LastLabel": "2024-25",
  "full82LastSeasonNumber": 20,
  "full82LastTeam": "Spurs",
  "playoffGames": 149,
  "playoffPoints": 2981,
  "playoffAssists": 1233,
  "playoffPointsPerGame": 20,
  "playoffAssistsPerGame": 8.3,
  "leaderCount": 8,
  "assistsAllTimeRank": 2,
  "stealsAllTimeRank": 2,
  "pointsRankAmongLeaders": 3,
  "assistLeaderName": "John Stockton",
  "assistsBehindLeader": 3254
};
