// app/data/game7Data.ts
//
// GENERATED by scripts/generate-game7-data.ts. Do not hand-edit.
// Game 7 and elimination-game performance computed from data/PlayerStatistics.csv
// game logs (Kaggle, Eoin A Moore, CC0). Playoff games only (gameId prefix 4);
// Play-In and NBA Cup excluded. basePpg is the player's own non-Game-7 playoff
// scoring in the same postseasons, weighted by Game 7 exposure; diff =
// coveredG7Ppg - basePpg and is null when covered years span < 75% of his
// Game 7s or a season lacks 3+ other playoff games. Points, rebounds and
// assists are complete in every era; minutes and attempts are not (pre-1980),
// so no efficiency or per-minute stats appear here. Elimination games: a team
// entered the game one loss from being out (winsNeeded - 1 opponent wins);
// every Game 7 counts for both teams. Current through the 2026 playoffs.

export interface Game7Player {
  personId: number;
  name: string;
  g7G: number;
  wins: number;
  losses: number;
  g7Ppg: number;
  g7Rpg: number;
  g7Apg: number;
  basePpg: number | null;
  coveredG7Ppg: number | null;
  diff: number | null;
  firstYear: number;
  lastYear: number;
}

export interface Game7SingleGame {
  personId: number;
  name: string;
  year: number;
  date: string;
  round: string;
  team: string;
  opponent: string;
  pts: number;
  reb: number;
  ast: number;
  win: boolean;
}

export interface ElimPlayer {
  personId: number;
  name: string;
  elimG: number;
  elimWins: number;
  elimLosses: number;
  elimPpg: number;
  firstYear: number;
  lastYear: number;
}

export interface HomeDecade {
  decade: string;
  games: number;
  homeWins: number;
  homeWinPct: number;
}

export const leagueContext = {
  totalGame7s: 159,
  firstYear: 1951,
  lastYear: 2026,
  homeKnownGames: 159,
  homeWins: 117,
  homeLosses: 42,
  homeWinPct: 74,
  avgG7TeamScore: 98.7,
  avgEarlierGamesTeamScore: 101.5,
  qualifiedPlayers: 685,
  avgDiff: -0.3,
  pctScoreLess: 56,
  elimTeamGames: 1626,
  elimQualified: 10
};

export const careerLeaders: Game7Player[] = [
  { personId: 201142, name: "Kevin Durant", g7G: 5, wins: 3, losses: 2, g7Ppg: 36.2, g7Rpg: 7.6, g7Apg: 3.6, basePpg: 29.5, coveredG7Ppg: 36.2, diff: 6.7, firstYear: 2011, lastYear: 2021 },
  { personId: 2544, name: "LeBron James", g7G: 8, wins: 6, losses: 2, g7Ppg: 34.9, g7Rpg: 9.9, g7Apg: 5.6, basePpg: 28.9, coveredG7Ppg: 34.9, diff: 6, firstYear: 2006, lastYear: 2018 },
  { personId: 78497, name: "Jerry West", g7G: 9, wins: 4, losses: 5, g7Ppg: 30.9, g7Rpg: 7.7, g7Apg: 6.1, basePpg: 29.7, coveredG7Ppg: 30.9, diff: 1.2, firstYear: 1961, lastYear: 1973 },
  { personId: 201939, name: "Stephen Curry", g7G: 6, wins: 4, losses: 2, g7Ppg: 30.8, g7Rpg: 7, g7Apg: 7, basePpg: 24.7, coveredG7Ppg: 30.8, diff: 6.1, firstYear: 2014, lastYear: 2025 },
  { personId: 1628983, name: "Shai Gilgeous-Alexander", g7G: 4, wins: 2, losses: 2, g7Ppg: 29.5, g7Rpg: 3.8, g7Apg: 7.3, basePpg: 25.6, coveredG7Ppg: 29.5, diff: 3.9, firstYear: 2020, lastYear: 2026 },
  { personId: 76127, name: "Elgin Baylor", g7G: 9, wins: 3, losses: 6, g7Ppg: 29.2, g7Rpg: 13.4, g7Apg: 3.8, basePpg: 27.6, coveredG7Ppg: 29.2, diff: 1.7, firstYear: 1960, lastYear: 1970 },
  { personId: 77847, name: "Bob Pettit", g7G: 6, wins: 2, losses: 4, g7Ppg: 29.2, g7Rpg: 16.2, g7Apg: 2.3, basePpg: 27, coveredG7Ppg: 29.2, diff: 2.1, firstYear: 1957, lastYear: 1964 },
  { personId: 1628378, name: "Donovan Mitchell", g7G: 4, wins: 3, losses: 1, g7Ppg: 27.3, g7Rpg: 6.8, g7Apg: 3.8, basePpg: 29.9, coveredG7Ppg: 27.3, diff: -2.7, firstYear: 2020, lastYear: 2026 },
  { personId: 165, name: "Hakeem Olajuwon", g7G: 5, wins: 4, losses: 1, g7Ppg: 27.2, g7Rpg: 13.6, g7Apg: 5.2, basePpg: 27.9, coveredG7Ppg: 27.2, diff: -0.7, firstYear: 1993, lastYear: 1997 },
  { personId: 77196, name: "Sam Jones", g7G: 9, wins: 9, losses: 0, g7Ppg: 27.1, g7Rpg: 5.6, g7Apg: 1.9, basePpg: 18.6, coveredG7Ppg: 27.1, diff: 8.5, firstYear: 1959, lastYear: 1969 },
  { personId: 1449, name: "Larry Bird", g7G: 8, wins: 6, losses: 2, g7Ppg: 27, g7Rpg: 9.3, g7Apg: 6.8, basePpg: 22.7, coveredG7Ppg: 27, diff: 4.3, firstYear: 1981, lastYear: 1992 },
  { personId: 1460, name: "James Worthy", g7G: 4, wins: 3, losses: 1, g7Ppg: 27, g7Rpg: 8.3, g7Apg: 5.3, basePpg: 19.3, coveredG7Ppg: 27, diff: 7.7, firstYear: 1984, lastYear: 1988 },
  { personId: 1717, name: "Dirk Nowitzki", g7G: 5, wins: 4, losses: 1, g7Ppg: 26.8, g7Rpg: 13.6, g7Apg: 1.6, basePpg: 23.8, coveredG7Ppg: 26.8, diff: 3, firstYear: 2003, lastYear: 2014 },
  { personId: 1628369, name: "Jayson Tatum", g7G: 7, wins: 5, losses: 2, g7Ppg: 26.7, g7Rpg: 9.3, g7Apg: 5.1, basePpg: 23.7, coveredG7Ppg: 26.7, diff: 3, firstYear: 2018, lastYear: 2023 },
  { personId: 406, name: "Shaquille O'Neal", g7G: 4, wins: 3, losses: 1, g7Ppg: 26.3, g7Rpg: 10.5, g7Apg: 2.5, basePpg: 26, coveredG7Ppg: 26.3, diff: 0.3, firstYear: 1995, lastYear: 2005 },
];

export const mostG7s: Game7Player[] = [
  { personId: 951, name: "Ray Allen", g7G: 11, wins: 7, losses: 4, g7Ppg: 14.5, g7Rpg: 3.5, g7Apg: 2.5, basePpg: 16, coveredG7Ppg: 14.5, diff: -1.4, firstYear: 2001, lastYear: 2013 },
  { personId: 1718, name: "Paul Pierce", g7G: 10, wins: 5, losses: 5, g7Ppg: 18.6, g7Rpg: 6, g7Apg: 2.6, basePpg: 17.7, coveredG7Ppg: 18.6, diff: 0.9, firstYear: 2005, lastYear: 2017 },
  { personId: 78049, name: "Bill Russell", g7G: 10, wins: 10, losses: 0, g7Ppg: 18.6, g7Rpg: 29.3, g7Apg: 3.7, basePpg: 17.2, coveredG7Ppg: 18.6, diff: 1.4, firstYear: 1957, lastYear: 1969 },
  { personId: 201143, name: "Al Horford", g7G: 10, wins: 7, losses: 3, g7Ppg: 11.4, g7Rpg: 9, g7Apg: 3.3, basePpg: 11.8, coveredG7Ppg: 11.4, diff: -0.4, firstYear: 2008, lastYear: 2023 },
  { personId: 78497, name: "Jerry West", g7G: 9, wins: 4, losses: 5, g7Ppg: 30.9, g7Rpg: 7.7, g7Apg: 6.1, basePpg: 29.7, coveredG7Ppg: 30.9, diff: 1.2, firstYear: 1961, lastYear: 1973 },
  { personId: 76127, name: "Elgin Baylor", g7G: 9, wins: 3, losses: 6, g7Ppg: 29.2, g7Rpg: 13.4, g7Apg: 3.8, basePpg: 27.6, coveredG7Ppg: 29.2, diff: 1.7, firstYear: 1960, lastYear: 1970 },
  { personId: 77196, name: "Sam Jones", g7G: 9, wins: 9, losses: 0, g7Ppg: 27.1, g7Rpg: 5.6, g7Apg: 1.9, basePpg: 18.6, coveredG7Ppg: 27.1, diff: 8.5, firstYear: 1959, lastYear: 1969 },
  { personId: 76375, name: "Wilt Chamberlain", g7G: 9, wins: 4, losses: 5, g7Ppg: 24.4, g7Rpg: 27, g7Apg: 4.7, basePpg: 23.2, coveredG7Ppg: 24.4, diff: 1.3, firstYear: 1962, lastYear: 1973 },
  { personId: 1627759, name: "Jaylen Brown", g7G: 9, wins: 6, losses: 3, g7Ppg: 18.3, g7Rpg: 6.1, g7Apg: 2.3, basePpg: 20.2, coveredG7Ppg: 18.3, diff: -1.9, firstYear: 2017, lastYear: 2026 },
  { personId: 201935, name: "James Harden", g7G: 9, wins: 5, losses: 4, g7Ppg: 18, g7Rpg: 5.7, g7Apg: 7.1, basePpg: 22.3, coveredG7Ppg: 18, diff: -4.3, firstYear: 2011, lastYear: 2026 },
];

export const g7Risers: Game7Player[] = [
  { personId: 1630241, name: "Sam Merrill", g7G: 3, wins: 3, losses: 0, g7Ppg: 14.7, g7Rpg: 2, g7Apg: 1.7, basePpg: 5.2, coveredG7Ppg: 14.7, diff: 9.5, firstYear: 2024, lastYear: 2026 },
  { personId: 134, name: "Kevin Johnson", g7G: 3, wins: 1, losses: 2, g7Ppg: 31, g7Rpg: 2.3, g7Apg: 10, basePpg: 22.3, coveredG7Ppg: 31, diff: 8.7, firstYear: 1993, lastYear: 1995 },
  { personId: 77196, name: "Sam Jones", g7G: 9, wins: 9, losses: 0, g7Ppg: 27.1, g7Rpg: 5.6, g7Apg: 1.9, basePpg: 18.6, coveredG7Ppg: 27.1, diff: 8.5, firstYear: 1959, lastYear: 1969 },
  { personId: 247, name: "Joe Dumars", g7G: 3, wins: 1, losses: 2, g7Ppg: 22.3, g7Rpg: 3, g7Apg: 4.7, basePpg: 13.9, coveredG7Ppg: 22.3, diff: 8.5, firstYear: 1987, lastYear: 1990 },
  { personId: 1460, name: "James Worthy", g7G: 4, wins: 3, losses: 1, g7Ppg: 27, g7Rpg: 8.3, g7Apg: 5.3, basePpg: 19.3, coveredG7Ppg: 27, diff: 7.7, firstYear: 1984, lastYear: 1988 },
  { personId: 76386, name: "Phil Chenier", g7G: 4, wins: 2, losses: 2, g7Ppg: 23.8, g7Rpg: 6.8, g7Apg: 1.5, basePpg: 16.1, coveredG7Ppg: 23.8, diff: 7.6, firstYear: 1974, lastYear: 1979 },
  { personId: 201142, name: "Kevin Durant", g7G: 5, wins: 3, losses: 2, g7Ppg: 36.2, g7Rpg: 7.6, g7Apg: 3.6, basePpg: 29.5, coveredG7Ppg: 36.2, diff: 6.7, firstYear: 2011, lastYear: 2021 },
  { personId: 2406, name: "Caron Butler", g7G: 3, wins: 3, losses: 0, g7Ppg: 15.3, g7Rpg: 6, g7Apg: 1, basePpg: 8.8, coveredG7Ppg: 15.3, diff: 6.5, firstYear: 2004, lastYear: 2014 },
  { personId: 76107, name: "Dick Barnett", g7G: 4, wins: 3, losses: 1, g7Ppg: 23.3, g7Rpg: 1.5, g7Apg: 1.5, basePpg: 17, coveredG7Ppg: 23.3, diff: 6.3, firstYear: 1963, lastYear: 1971 },
  { personId: 2037, name: "Jamal Crawford", g7G: 5, wins: 3, losses: 2, g7Ppg: 19.4, g7Rpg: 2, g7Apg: 2.6, basePpg: 13.2, coveredG7Ppg: 19.4, diff: 6.2, firstYear: 2010, lastYear: 2017 },
];

export const g7Fallers: Game7Player[] = [
  { personId: 78126, name: "Bill Sharman", g7G: 3, wins: 3, losses: 0, g7Ppg: 10, g7Rpg: 3.3, g7Apg: 2.7, basePpg: 20.3, coveredG7Ppg: 10, diff: -10.3, firstYear: 1957, lastYear: 1960 },
  { personId: 600013, name: "Rick Barry", g7G: 3, wins: 1, losses: 2, g7Ppg: 19, g7Rpg: 6.3, g7Apg: 3.3, basePpg: 27.6, coveredG7Ppg: 19, diff: -8.6, firstYear: 1975, lastYear: 1977 },
  { personId: 76882, name: "Hal Greer", g7G: 4, wins: 0, losses: 4, g7Ppg: 12.5, g7Rpg: 7, g7Apg: 5.3, basePpg: 20.8, coveredG7Ppg: 12.5, diff: -8.3, firstYear: 1959, lastYear: 1971 },
  { personId: 978, name: "Peja Stojakovic", g7G: 4, wins: 0, losses: 4, g7Ppg: 10, g7Rpg: 7, g7Apg: 1.5, basePpg: 18.1, coveredG7Ppg: 10, diff: -8.1, firstYear: 2002, lastYear: 2008 },
  { personId: 1628973, name: "Jalen Brunson", g7G: 3, wins: 1, losses: 2, g7Ppg: 14.3, g7Rpg: 3.3, g7Apg: 4, basePpg: 21.4, coveredG7Ppg: 14.3, diff: -7, firstYear: 2021, lastYear: 2024 },
  { personId: 78150, name: "James Silas", g7G: 3, wins: 1, losses: 2, g7Ppg: 11, g7Rpg: 2, g7Apg: 3.3, basePpg: 17.4, coveredG7Ppg: 11, diff: -6.4, firstYear: 1979, lastYear: 1981 },
  { personId: 76970, name: "John Havlicek", g7G: 8, wins: 6, losses: 2, g7Ppg: 16.3, g7Rpg: 9, g7Apg: 4.1, basePpg: 22.2, coveredG7Ppg: 16.3, diff: -6, firstYear: 1963, lastYear: 1977 },
  { personId: 77554, name: "Jim McMillian", g7G: 3, wins: 2, losses: 1, g7Ppg: 10.7, g7Rpg: 2.3, g7Apg: 1.3, basePpg: 16.4, coveredG7Ppg: 10.7, diff: -5.8, firstYear: 1971, lastYear: 1975 },
  { personId: 977, name: "Kobe Bryant", g7G: 6, wins: 5, losses: 1, g7Ppg: 22.2, g7Rpg: 8, g7Apg: 5, basePpg: 27.9, coveredG7Ppg: 22.2, diff: -5.7, firstYear: 2000, lastYear: 2012 },
  { personId: 22, name: "Rik Smits", g7G: 4, wins: 1, losses: 3, g7Ppg: 13.5, g7Rpg: 4.3, g7Apg: 1.3, basePpg: 18.7, coveredG7Ppg: 13.5, diff: -5.2, firstYear: 1994, lastYear: 1998 },
];

export const topSingleGames: Game7SingleGame[] = [
  { personId: 1628369, name: "Jayson Tatum", year: 2023, date: "2023-05-14", round: "Conf. Semifinals", team: "Celtics", opponent: "76ers", pts: 51, reb: 13, ast: 5, win: true },
  { personId: 201939, name: "Stephen Curry", year: 2023, date: "2023-04-30", round: "First Round", team: "Warriors", opponent: "Kings", pts: 50, reb: 8, ast: 6, win: true },
  { personId: 201142, name: "Kevin Durant", year: 2021, date: "2021-06-19", round: "Conf. Semifinals", team: "Nets", opponent: "Bucks", pts: 48, reb: 9, ast: 6, win: false },
  { personId: 77196, name: "Sam Jones", year: 1963, date: "1963-04-10", round: "Conf. Finals", team: "Celtics", opponent: "Royals", pts: 47, reb: 7, ast: 1, win: true },
  { personId: 1122, name: "Dominique Wilkins", year: 1988, date: "1988-05-22", round: "Conf. Semifinals", team: "Hawks", opponent: "Celtics", pts: 47, reb: 5, ast: 3, win: false },
  { personId: 1629029, name: "Luka Doncic", year: 2021, date: "2021-06-06", round: "First Round", team: "Mavericks", opponent: "Clippers", pts: 46, reb: 7, ast: 14, win: false },
  { personId: 134, name: "Kevin Johnson", year: 1995, date: "1995-05-20", round: "Conf. Semifinals", team: "Suns", opponent: "Rockets", pts: 46, reb: 3, ast: 10, win: false },
  { personId: 2544, name: "LeBron James", year: 2018, date: "2018-04-29", round: "First Round", team: "Cavaliers", opponent: "Pacers", pts: 45, reb: 8, ast: 7, win: true },
  { personId: 2544, name: "LeBron James", year: 2008, date: "2008-05-18", round: "Conf. Semifinals", team: "Cavaliers", opponent: "Celtics", pts: 45, reb: 5, ast: 6, win: false },
  { personId: 787, name: "Charles Barkley", year: 1993, date: "1993-06-05", round: "Conf. Finals", team: "Suns", opponent: "SuperSonics", pts: 44, reb: 24, ast: 1, win: true },
  { personId: 947, name: "Allen Iverson", year: 2001, date: "2001-06-03", round: "Conf. Finals", team: "76ers", opponent: "Bucks", pts: 44, reb: 6, ast: 7, win: true },
  { personId: 600015, name: "Oscar Robertson", year: 1963, date: "1963-04-10", round: "Conf. Finals", team: "Royals", opponent: "Celtics", pts: 43, reb: 6, ast: 6, win: false },
];

export const topRebGames: Game7SingleGame[] = [
  { personId: 78049, name: "Bill Russell", year: 1962, date: "1962-04-18", round: "NBA Finals", team: "Celtics", opponent: "Lakers", pts: 30, reb: 40, ast: 4, win: true },
  { personId: 78049, name: "Bill Russell", year: 1960, date: "1960-04-09", round: "NBA Finals", team: "Celtics", opponent: "Hawks", pts: 22, reb: 35, ast: 4, win: true },
  { personId: 76375, name: "Wilt Chamberlain", year: 1968, date: "1968-04-19", round: "Conf. Finals", team: "76ers", opponent: "Celtics", pts: 14, reb: 34, ast: 5, win: false },
];

export const topAstGames: Game7SingleGame[] = [
  { personId: 304, name: "John Stockton", year: 1988, date: "1988-05-21", round: "Conf. Semifinals", team: "Jazz", opponent: "Lakers", pts: 29, reb: 1, ast: 20, win: false },
  { personId: 76750, name: "Walt Frazier", year: 1970, date: "1970-05-08", round: "NBA Finals", team: "Knicks", opponent: "Lakers", pts: 36, reb: 7, ast: 19, win: true },
  { personId: 470, name: "Doc Rivers", year: 1988, date: "1988-05-22", round: "Conf. Semifinals", team: "Hawks", opponent: "Celtics", pts: 16, reb: 5, ast: 18, win: false },
];

export const elimLeaders: ElimPlayer[] = [
  { personId: 2544, name: "LeBron James", elimG: 30, elimWins: 15, elimLosses: 15, elimPpg: 32.8, firstYear: 2006, lastYear: 2026 },
  { personId: 893, name: "Michael Jordan", elimG: 13, elimWins: 6, elimLosses: 7, elimPpg: 31.3, firstYear: 1985, lastYear: 1998 },
  { personId: 76375, name: "Wilt Chamberlain", elimG: 23, elimWins: 12, elimLosses: 11, elimPpg: 31.1, firstYear: 1960, lastYear: 1973 },
  { personId: 201142, name: "Kevin Durant", elimG: 16, elimWins: 6, elimLosses: 10, elimPpg: 29.9, firstYear: 2010, lastYear: 2024 },
  { personId: 947, name: "Allen Iverson", elimG: 14, elimWins: 6, elimLosses: 8, elimPpg: 29.8, firstYear: 1999, lastYear: 2008 },
  { personId: 78497, name: "Jerry West", elimG: 24, elimWins: 13, elimLosses: 11, elimPpg: 29.3, firstYear: 1961, lastYear: 1973 },
  { personId: 201939, name: "Stephen Curry", elimG: 15, elimWins: 10, elimLosses: 5, elimPpg: 28.9, firstYear: 2013, lastYear: 2025 },
  { personId: 76804, name: "George Gervin", elimG: 14, elimWins: 6, elimLosses: 8, elimPpg: 27.9, firstYear: 1977, lastYear: 1985 },
  { personId: 76127, name: "Elgin Baylor", elimG: 24, elimWins: 13, elimLosses: 11, elimPpg: 27.8, firstYear: 1959, lastYear: 1970 },
  { personId: 1628378, name: "Donovan Mitchell", elimG: 12, elimWins: 4, elimLosses: 8, elimPpg: 27.7, firstYear: 2018, lastYear: 2026 },
];

export const homeByDecade: HomeDecade[] = [
  { decade: "1950s", games: 6, homeWins: 6, homeWinPct: 100 },
  { decade: "1960s", games: 13, homeWins: 11, homeWinPct: 85 },
  { decade: "1970s", games: 23, homeWins: 18, homeWinPct: 78 },
  { decade: "1980s", games: 15, homeWins: 12, homeWinPct: 80 },
  { decade: "1990s", games: 18, homeWins: 16, homeWinPct: 89 },
  { decade: "2000s", games: 28, homeWins: 20, homeWinPct: 71 },
  { decade: "2010s", games: 31, homeWins: 23, homeWinPct: 74 },
  { decade: "2020s", games: 25, homeWins: 11, homeWinPct: 44 },
];
