// scripts/generate-player-directory.ts
//
// Regenerates app/data/playerDirectory.ts: the set of "notable" players used to
// build the crawlable A-Z player directory at /players. A young domain will not
// spend crawl budget graph-walking to all ~5,600 player pages, so this tier caps
// the directory to players with a real career (games/points threshold) and gives
// crawlers a shallow, complete path to those pages. Rerun after a new season:
//   npm run generate:player-directory
//
// Self-contained: aggregates career games/points straight from regularseasonstats
// (one row per player-season), no RPC required.

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { config } from 'dotenv';
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../types/supabase';

config({ path: resolve(process.cwd(), '.env.local') });
config({ path: resolve(process.cwd(), '.env') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!supabaseUrl) throw new Error('NEXT_PUBLIC_SUPABASE_URL is required.');
if (!serviceRoleKey) throw new Error('SUPABASE_SERVICE_ROLE_KEY is required.');

const supabase = createClient<Database>(supabaseUrl, serviceRoleKey, {
  auth: { persistSession: false, autoRefreshToken: false },
});

const PAGE_SIZE = 1000;
// Tier dial: a player qualifies with either a long career or heavy scoring.
const MIN_GAMES = 400;
const MIN_POINTS = 5000;
const OUTPUT_PATH = resolve(process.cwd(), 'app/data/playerDirectory.ts');

type SeasonRow = {
  personId: number;
  firstName: string | null;
  lastName: string | null;
  G: number | null;
  PTS_total: number | null;
};

interface Agg {
  id: number;
  firstName: string;
  lastName: string;
  games: number;
  points: number;
}

async function fetchAll(): Promise<SeasonRow[]> {
  const rows: SeasonRow[] = [];
  for (let from = 0; ; from += PAGE_SIZE) {
    const { data, error } = await supabase
      .from('regularseasonstats')
      .select('personId, firstName, lastName, G, PTS_total')
      .range(from, from + PAGE_SIZE - 1);
    if (error) throw new Error(`Failed reading regularseasonstats: ${error.message}`);
    if (!data || data.length === 0) break;
    rows.push(...(data as SeasonRow[]));
    if (data.length < PAGE_SIZE) break;
  }
  return rows;
}

// First alphabetic character of the last name (fallback: first name), uppercased.
// Players whose surname starts with a non-letter are dropped from the A-Z tier.
function letterOf(lastName: string, firstName: string): string | null {
  const source = lastName || firstName;
  const m = source.normalize('NFD').replace(/\p{Diacritic}/gu, '').match(/[a-zA-Z]/);
  return m ? m[0].toUpperCase() : null;
}

async function main() {
  console.log('Scanning regularseasonstats…');
  const seasonRows = await fetchAll();

  const byId = new Map<number, Agg>();
  for (const r of seasonRows) {
    let a = byId.get(r.personId);
    if (!a) {
      a = { id: r.personId, firstName: '', lastName: '', games: 0, points: 0 };
      byId.set(r.personId, a);
    }
    a.games += r.G ?? 0;
    a.points += r.PTS_total ?? 0;
    // Keep the first non-empty name we see; season rows are consistent per player.
    if (!a.firstName && r.firstName) a.firstName = r.firstName;
    if (!a.lastName && r.lastName) a.lastName = r.lastName;
  }

  const notable = [...byId.values()].filter(
    (a) => a.games >= MIN_GAMES || a.points >= MIN_POINTS,
  );

  const rows = notable
    .map((a) => {
      const name = `${a.firstName} ${a.lastName}`.trim();
      const letter = letterOf(a.lastName, a.firstName);
      return letter && name ? { id: a.id, name, letter, points: Math.round(a.points), games: a.games } : null;
    })
    .filter((r): r is NonNullable<typeof r> => r !== null);

  // Sort by last name, then first name (case-insensitive) for stable A-Z listing.
  rows.sort((x, y) => {
    const lx = x.name.split(' ').slice(-1)[0].toLowerCase();
    const ly = y.name.split(' ').slice(-1)[0].toLowerCase();
    return lx.localeCompare(ly) || x.name.toLowerCase().localeCompare(y.name.toLowerCase());
  });

  const counts = new Map<string, number>();
  for (const r of rows) counts.set(r.letter, (counts.get(r.letter) ?? 0) + 1);

  const body = rows
    .map(
      (r) =>
        `  { id: ${r.id}, name: ${JSON.stringify(r.name)}, letter: ${JSON.stringify(
          r.letter,
        )}, points: ${r.points}, games: ${r.games} },`,
    )
    .join('\n');

  const file = `// app/data/playerDirectory.ts
//
// GENERATED by scripts/generate-player-directory.ts — do not edit by hand.
// Notable players (career games >= ${MIN_GAMES} OR career points >= ${MIN_POINTS})
// with a /player/[id] profile, used to build the crawlable A-Z directory at
// /players. Rerun \`npm run generate:player-directory\` after a new season.

export interface DirectoryPlayer {
  id: number;
  name: string;
  letter: string;
  points: number;
  games: number;
}

export const PLAYER_DIRECTORY: DirectoryPlayer[] = [
${body}
];
`;

  writeFileSync(OUTPUT_PATH, file);
  console.log(`Wrote ${rows.length} notable players to ${OUTPUT_PATH}`);
  console.log(
    'Per-letter counts:',
    [...counts.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([l, n]) => `${l}:${n}`).join(' '),
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
